- id: orbit-pt256-160
  desc: "Streams for orbit, pt256, 160x120 resolution."
  code: 
  - diffeoplan.library.logs.BagStream
  - files:
    - ~/diffeo-data/processed-data/160x120nz/orbit-pt256z2-indoor.600s.processed.bag
    - ~/diffeo-data/processed-data/160x120nz/orbit-pt256z2-outdoor.600s1.processed.bag
    - ~/diffeo-data/processed-data/160x120nz/orbit-pt256z2-window.600s2.processed.bag
    - ~/diffeo-data/processed-data/160x120nz/orbit-pt256z2-window.600s.processed.bag

- id: orbit-pt256-80
  desc: "Streams for orbit, pt256, 80x60 resolution."
  code: 
  - diffeoplan.library.logs.BagStream
  - files:
    - ~/diffeo-data/processed-data/80x60nz/orbit-pt256z2-indoor.600s.processed.bag
    - ~/diffeo-data/processed-data/80x60nz/orbit-pt256z2-outdoor.600s1.processed.bag
    - ~/diffeo-data/processed-data/80x60nz/orbit-pt256z2-window.600s2.processed.bag
    - ~/diffeo-data/processed-data/80x60nz/orbit-pt256z2-window.600s.processed.bag

- id: orbit-pt256-40
  desc: "Streams for orbit, pt256, 40x30 resolution."
  code: 
  - diffeoplan.library.logs.BagStream
  - files:
    - ~/diffeo-data/processed-data/40x30nz/orbit-pt256z2-indoor.600s.processed.bag
    - ~/diffeo-data/processed-data/40x30nz/orbit-pt256z2-outdoor.600s1.processed.bag
    - ~/diffeo-data/processed-data/40x30nz/orbit-pt256z2-window.600s2.processed.bag
    - ~/diffeo-data/processed-data/40x30nz/orbit-pt256z2-window.600s.processed.bag
    
- id: orbit-pt256-20
  desc: "Streams for orbit, pt256, 20x15 resolution."
  code: 
  - diffeoplan.library.logs.BagStream
  - files:
    - ~/diffeo-data/processed-data/20x15nz/orbit-pt256z2-indoor.600s-20x15.processed.bag
    #- ~/diffeo-data/processed-data/20x15nz/orbit-pt256z2-outdoor.600s1.processed.bag
    #- ~/diffeo-data/processed-data/20x15nz/orbit-pt256z2-window.600s2-20x15.processed.bag
    #- ~/diffeo-data/processed-data/20x15nz/orbit-pt256z2-window.600s-20x15.processed.bag


- id: orbit-pt256z2-160
  desc: "Streams for orbit, pt256z2, 160x120 resolution."
  code: 
  - diffeoplan.library.logs.BagStream
  - files:
    - ~/diffeo-data/processed-data/160x120/orbit-pt256z2-indoor.600s.processed.bag
    - ~/diffeo-data/processed-data/160x120/orbit-pt256z2-outdoor.600s1.processed.bag
    - ~/diffeo-data/processed-data/160x120/orbit-pt256z2-window.600s2.processed.bag
    - ~/diffeo-data/processed-data/160x120/orbit-pt256z2-window.600s.processed.bag
  

- id: orbit-pt64-160
  desc: "Streams for orbit, pt64, 160x120 resolution."
  code: 
  - diffeoplan.library.logs.BagStream
  - files: 
    - ~/diffeo-data/processed-data/orbit-pt64-window1-160x120.processed.bag  
    - ~/diffeo-data/processed-data/orbit-pt64-window2-160x120.processed.bag  
    - ~/diffeo-data/processed-data/orbit-pt64-window3-160x120.processed.bag  
  

- id: orbit-pt64-40
  desc: "Streams for orbit, pt64, 40x30 resolution."
  code: 
  - diffeoplan.library.logs.BagStream
  - files: 
    - ~/diffeo-data/processed-data/orbit-pt64-window1-40x30.processed.bag  
    - ~/diffeo-data/processed-data/orbit-pt64-window2-40x30.processed.bag  
    - ~/diffeo-data/processed-data/orbit-pt64-window3-40x30.processed.bag  

- id: orbit-pt256z50-40
  desc: "Streams for orbit, pt256, 80x60 resolution, zoom between 100 and 200 in size 50 steps."
  code: 
  - diffeoplan.library.logs.BagStream
  - files: 
    - ~/diffeo-data/processed-data/z50/orbit-pt256z2-indoor.600s-40x30.processed.bag
    - ~/diffeo-data/processed-data/z50/orbit-pt256z2-outdoor.600s1-40x30.processed.bag
    - ~/diffeo-data/processed-data/z50/orbit-pt256z2-window.600s-40x30.processed.bag
    - ~/diffeo-data/processed-data/z50/orbit-pt256z2-window.600s2-40x30.processed.bag

